# MongoDB 配置文件
# 副本集模式 + 认证

storage:
  dbPath: /data/db
  journal:
    enabled: true
  wiredTiger:
    engineConfig:
      cacheSizeGB: 1

systemLog:
  destination: file
  path: /var/log/mongodb/mongod.log
  logAppend: true

net:
  port: 27017
  bindIpAll: true

replication:
  replSetName: tcm-replSet

security:
  authorization: enabled

operationProfiling:
  mode: slowOp
  slowOpThresholdMs: 100
